####### iox9 config file #############################
# Use this file to configure the framework. 
# Essentially:                    
# 
# - Define general preferences.
# - Register your data sources (cameras, for example).
# - Register your statistical processors.
# - Register your views and tell them how to interact
#   with sources and statistical processors.
# - Register your notification agents.
######################################################

# General preferences
capacity: 30 
almost_full: 25

# Database configuration
database:
    url: "jdbc:postgresql://localhost:5432/rapx9db"
    username: "rapx9"
    password: "123"

# Important concrete classes
entity_dao_class: "pso.secondphase.iox9.dao.JDBCEntityDAO"
iorecord_dao_class: "pso.secondphase.iox9.dao.JDBCIORecordDAO"
model_factory_class: "pso.secondphase.iox9.model.GeneralModelFactory"

# Collecto configuration
collector:
    class: "pso.secondphase.iox9.business.processing.SinespInformationCollector"
    sleep_time: 30000
    
# Sources list
sources:
    - 
        id: entrance_camera
        source_class: "pso.secondphase.iox9.business.capture.InDataSourceSavedImage"
        processor_class: "pso.secondphase.iox9.business.processing.VehicleInProcessor"
        recognizer_class: "pso.secondphase.iox9.business.processing.OpenCVUFRNLicensePlateReconizer"
        io_type: 0
        active: true
        sleep_time: 1000
    -
        id: exit_camera
        source_class: "pso.secondphase.iox9.business.capture.OutDataSourceSavedImage"
        processor_class: "pso.secondphase.iox9.business.processing.VehicleOutProcessor"
        recognizer_class: "pso.secondphase.iox9.business.processing.OpenCVUFRNLicensePlateReconizer"
        io_type: 1
        active: true
        sleep_time: 5000

# Statistics processors registration
statictics_processors:
    -
        id: count_by_hours_in_day
        class: "pso.secondphase.iox9.business.statistics.CountByHoursInDayStatistics"
    -
        id: count_by_week_days
        class: "pso.secondphase.iox9.business.statistics.CountByWeekDaysStatistics"
    -
        id: price_by_hours_in_day
        class: "pso.secondphase.iox9.business.statistics.PriceByHoursInDayStatistics"

notification_agents:
    -
        id: daily_visitors
        class: "pso.secondphase.iox9.business.notification.DailyVisitorsGoalNotificationAgent"
    -
        id: max_capacity
        class: "pso.secondphase.iox9.business.notification.MaxCapacityNotificationAgent"
    -
        id: stolen_car
        class: "pso.secondphase.iox9.business.notification.StolenCarNotificationAgent"

# Views registration
views:
    -
        id: entrance_panel
        class: "pso.secondphase.rapx9.view.VehicleInPanel"
        notifiable: false
        processors_of_interest:
            - entrance_camera
    -
        id: exit_panel
        class: "pso.secondphase.rapx9.view.VehicleOutPanel"
        notifiable: false
        processors_of_interest:
            - exit_camera

# Start class
start_class: "pso.secondphase.rapx9.view.RealTimePanel"
