####### iox9 config file #############################
# Use this file to configure the framework. 
# Essentially:                    
# 
# - Define general preferences.
# - Register your data sources (cameras, for example).
# - Register your statistical processors.
# - Register your views and tell them how to interact
#   with sources and statistical processors.
# - Register your notification agents.
######################################################

# General preferences
capacity: 30 
almost_full: 25

entity_dao_class: "pso.secondphase.iox9.dao.JDBCEntityDAO"
iorecord_dao_class: "pso.secondphase.iox9.dao.JDBCIORecordDAO"
model_factory_class: "pso.secondphase.iox9.model.GeneralModelFactory"

# Sources list
sources:
    - 
        id: entrance_camera
        source_class: "pso.secondphase.iox9.business.capture.SarxosAddressCameraDataSource"
        processor_class: "InProcessor"
        recognizer_class: "RecognizerClass"
        io_type: 1
        active: true
        sleep_time: 1000
        parameters:
            address: "192.168.7.7"
    -
        id: exit_camera
        source_class: "pso.secondphase.iox9.business.capture.SarxosAddressCameraDataSource"
        processor_class: "OutProcessor"
        recognizer_class: "RecognizerClass"
        io_type: 0
        active: true
        sleep_time: 1000
        parameters:
            address: "192.168.7.6"

# Statistics processors registration
statictics_processors:
    -
        id: weekly_statistics
        class: "WeeklyStatistics"
    -
        id: length_of_stay
        class: "LenghtOfStay"

notification_agents:
    -
        id: entrance_goal
        class: "EntranceGoalNotificationAgent"
    -
        id: almost_full_alert
        class: "AlmostFullNotificationAgent"

# Views registration
views:
    -
        id: entrance_panel
        class: "PanelIn"
        notifiable: true
        publishers:
            - entrance_camera
    -
        id: exit_panel
        class: "PanelOut"
        publishers:
            - exit_camera


